
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package bumh3r.utils;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IDENTIFICADOR = 39;
  public static final int INTERNAL = 14;
  public static final int DIVISION = 65;
  public static final int MENOR_IGUAL = 76;
  public static final int ARROW = 58;
  public static final int CONST = 20;
  public static final int PARENTESIS_CIERRE = 47;
  public static final int RANGE_INCLUSIVE = 60;
  public static final int MAYOR = 75;
  public static final int ENUM = 10;
  public static final int LATEINIT = 21;
  public static final int DIFERENTE = 73;
  public static final int CATCH = 32;
  public static final int THROW = 34;
  public static final int NUMERO_DECIMAL = 40;
  public static final int PROTECTED = 13;
  public static final int NOT = 71;
  public static final int FALSE = 36;
  public static final int COMENTARIO = 54;
  public static final int OBJECT = 5;
  public static final int VAR = 19;
  public static final int FINAL = 16;
  public static final int DOS_PUNTOS = 45;
  public static final int PACKAGE = 2;
  public static final int VAL = 18;
  public static final int WHEN = 24;
  public static final int CLASS = 4;
  public static final int LLAVE_CIERRE = 49;
  public static final int INCREMENTO = 67;
  public static final int COMA = 52;
  public static final int ABSTRACT = 9;
  public static final int MODULO = 66;
  public static final int TRUE = 35;
  public static final int IGUAL = 72;
  public static final int WHILE = 26;
  public static final int INTERFACE = 6;
  public static final int DO = 27;
  public static final int FOR = 25;
  public static final int DECREMENTO = 68;
  public static final int PUBLIC = 11;
  public static final int RETURN = 30;
  public static final int ELSE = 23;
  public static final int TRY = 31;
  public static final int MENOS = 62;
  public static final int MENOR = 74;
  public static final int MAS = 63;
  public static final int BREAK = 28;
  public static final int FUN = 17;
  public static final int SAFE_CALL = 56;
  public static final int NULL = 37;
  public static final int EOF = 0;
  public static final int PUNTO_Y_COMA = 44;
  public static final int PUNTO = 53;
  public static final int SEALED = 8;
  public static final int IMPORT = 3;
  public static final int NULLABLE = 57;
  public static final int LLAVE_APERTURA = 48;
  public static final int TIPO_DATOS = 38;
  public static final int OR = 70;
  public static final int error = 1;
  public static final int DATA = 7;
  public static final int FINALLY = 33;
  public static final int CONTINUE = 29;
  public static final int IF = 22;
  public static final int PARENTESIS_APERTURA = 46;
  public static final int NUMERICO = 41;
  public static final int MULTIPLICACION = 64;
  public static final int CORCHETE_APER = 50;
  public static final int ASIGNACION = 43;
  public static final int CADENA = 42;
  public static final int RANGE = 59;
  public static final int IN_RANGE = 78;
  public static final int AND = 69;
  public static final int OPEN = 15;
  public static final int CORCHETE_CIERRE = 51;
  public static final int PRIVATE = 12;
  public static final int RANGE_EXCLUSIVE = 61;
  public static final int MAYOR_IGUAL = 77;
  public static final int ELVIS = 55;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PACKAGE",
  "IMPORT",
  "CLASS",
  "OBJECT",
  "INTERFACE",
  "DATA",
  "SEALED",
  "ABSTRACT",
  "ENUM",
  "PUBLIC",
  "PRIVATE",
  "PROTECTED",
  "INTERNAL",
  "OPEN",
  "FINAL",
  "FUN",
  "VAL",
  "VAR",
  "CONST",
  "LATEINIT",
  "IF",
  "ELSE",
  "WHEN",
  "FOR",
  "WHILE",
  "DO",
  "BREAK",
  "CONTINUE",
  "RETURN",
  "TRY",
  "CATCH",
  "FINALLY",
  "THROW",
  "TRUE",
  "FALSE",
  "NULL",
  "TIPO_DATOS",
  "IDENTIFICADOR",
  "NUMERO_DECIMAL",
  "NUMERICO",
  "CADENA",
  "ASIGNACION",
  "PUNTO_Y_COMA",
  "DOS_PUNTOS",
  "PARENTESIS_APERTURA",
  "PARENTESIS_CIERRE",
  "LLAVE_APERTURA",
  "LLAVE_CIERRE",
  "CORCHETE_APER",
  "CORCHETE_CIERRE",
  "COMA",
  "PUNTO",
  "COMENTARIO",
  "ELVIS",
  "SAFE_CALL",
  "NULLABLE",
  "ARROW",
  "RANGE",
  "RANGE_INCLUSIVE",
  "RANGE_EXCLUSIVE",
  "MENOS",
  "MAS",
  "MULTIPLICACION",
  "DIVISION",
  "MODULO",
  "INCREMENTO",
  "DECREMENTO",
  "AND",
  "OR",
  "NOT",
  "IGUAL",
  "DIFERENTE",
  "MENOR",
  "MAYOR",
  "MENOR_IGUAL",
  "MAYOR_IGUAL",
  "IN_RANGE"
  };
}

